
# Generated by LINGO_to_Py.py
import lingo_api as lingo
import numpy as np
import pandas as pd
    
uData =  {'Prefix':'Lingo API', 'LastIter':-1,}
# Setting a default cbError function to catch any errors in
def cbError(pEnv, uData, nErrorCode, errorText):
    raise lingo.CallBackError(nErrorCode, errorText)

# Callback solver 
def cbSolver(pEnv, nReserved, uData):
    # Allocate the numpy arrays for API callback getter functions
    nIters   = np.array([-1],dtype=np.int32)

    # Get the current iteration
    errorcode = lingo.pyLSgetIntCallbackInfoLng(pEnv, lingo.LS_IINFO_ITERATIONS_LNG, nIters)
    
    if nIters[0] > 0 and uData["LastIter"] < nIters[0]:
        # update the LastIter saved in uData
        uData["LastIter"] = nIters[0]
        callbackStr = f"{uData['Prefix']:15} Iteration: {nIters[0]}"
        print(callbackStr)
    return 0
    

# Path to LINGO file
lngFile = 'chess.lng'


# Define model data:
# Set data
NUTS = 
# Set data
BRANDS = 
# supply is an attribute of set nuts
SUPPLY = 
# price is an attribute of set brands
PRICE = 
# formula is an attribute of set ncrossb(nuts,brands)
FORMULA = 
# Var data
PRODUCE = 
# Var data
STATUS = 


# Create a model object
model = lingo.Model(lngFile)

# Add pointer data to model
model.set_pointer('Pointer1',NUTS,lingo.SET)
model.set_pointer('Pointer2',BRANDS,lingo.SET)
model.set_pointer('Pointer3',SUPPLY,lingo.PARAM)
model.set_pointer('Pointer4',PRICE,lingo.PARAM)
model.set_pointer('Pointer5',FORMULA,lingo.PARAM)
model.set_pointer('Pointer6',PRODUCE,lingo.VAR)
model.set_pointer('Pointer7',STATUS,lingo.VAR)


# Set the call back function and user data
model.set_cbError(cbError)
model.set_cbSolver(cbSolver)
model.set_uData(uData)
# Now that everything is set call solve(model)
lingo.solve(model)
