
# Generated by LINGO_to_Py.py
import lingo_api as lingo
import numpy as np
import pandas as pd
    
uData =  {'Prefix':'Lingo API', 'LastIter':-1,}
# Setting a default cbError function to catch any errors in
def cbError(pEnv, uData, nErrorCode, errorText):
    raise lingo.CallBackError(nErrorCode, errorText)

# Callback solver 
def cbSolver(pEnv, nReserved, uData):
    # Allocate the numpy arrays for API callback getter functions
    nIters   = np.array([-1],dtype=np.int32)

    # Get the current iteration
    errorcode = lingo.pyLSgetIntCallbackInfoLng(pEnv, lingo.LS_IINFO_ITERATIONS_LNG, nIters)
    
    if nIters[0] > 0 and uData["LastIter"] < nIters[0]:
        # update the LastIter saved in uData
        uData["LastIter"] = nIters[0]
        callbackStr = f"{uData['Prefix']:15} Iteration: {nIters[0]}"
        print(callbackStr)
    return 0
    

# Path to LINGO file
lngFile = 'dedicatedportfolio.lng'


# Define model data:
# Var data
NUM_LIABILITIES = 
# Set data
BONDS = 
# price is an attribute of set bonds
PRICE = 
# l is an attribute of set liabilities/1..num_liabilities/
L = 
# f is an attribute of set cashflow(bonds,liabilities)
F = 
# Var data
AMOUNT = 
# Var data
DUAL_PRICE = 
# Var data
STATUS = 


# Create a model object
model = lingo.Model(lngFile)

# Add pointer data to model
model.set_pointer('Pointer1',NUM_LIABILITIES,lingo.PARAM)
model.set_pointer('Pointer2',BONDS,lingo.SET)
model.set_pointer('Pointer3',PRICE,lingo.PARAM)
model.set_pointer('Pointer4',L,lingo.PARAM)
model.set_pointer('Pointer5',F,lingo.PARAM)
model.set_pointer('Pointer6',AMOUNT,lingo.VAR)
model.set_pointer('Pointer7',DUAL_PRICE,lingo.VAR)
model.set_pointer('Pointer8',STATUS,lingo.VAR)


# Set the call back function and user data
model.set_cbError(cbError)
model.set_cbSolver(cbSolver)
model.set_uData(uData)
# Now that everything is set call solve(model)
lingo.solve(model)
